version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "06:00"
    open-pull-requests-limit: 1
    reviewers:
      - Jamalam360
    assignees:
      - Jamalam360
