keys:
  - &hercules age1g3n4mvmsl9wku7307kk9p9mc8g70yw9drm6yz0evuze0kgv65pxqdup7ny
  - &lyra age1p34gq7amcr8ue6uwavxq45mg9fxvwgnr7uraul6juyyhqhqfmggs28p6gu
  - &leo age1qpjv8tesr04kau4na4qnjccwzpmwkrth7vmnntytteh2re6meurq2zmnlj
  - &ara age1vjqk60g3tjacffjhgptp9cuay8fxxwtq5f9skthzaeqacvzups2q69rrd5
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *hercules
          - *lyra
          - *leo
          - *ara
