{
  inputs,
  outputs,
  pkgs,
  config,
  ...
}: {
  imports = [
    inputs.home-manager.nixosModules.home-manager
    inputs.nix-minecraft.nixosModules.minecraft-servers

    ./hardware-configuration.nix
    ./disk-configuration.nix

    ./../../modules/nixos/base.nix
    ./../../services/lyra/discord-github-releases.nix
    ./../../services/lyra/nginx.nix
    ./../../services/lyra/reposilite.nix
    ./../../services/lyra/restic.nix
    ./../../services/lyra/sat-bot.nix
    ./../../services/lyra/static/cdn.nix
    ./../../services/lyra/static/its-clearing-up.nix
    ./../../services/lyra/static/teach-man-fish.nix
  ];

  nixpkgs.overlays = [
    inputs.nix-minecraft.overlay
    inputs.sculk.overlay
  ];

  # == System Configuration ==
  boot.loader.grub.enable = true;
  networking.hostName = "lyra";
  networking.networkmanager.enable = true;
  time.timeZone = "Europe/Berlin";

  # == Home Manager ==
  home-manager = {
    extraSpecialArgs = {inherit inputs outputs;};
    useGlobalPkgs = true;
    useUserPackages = true;
    users = {
      james = {
        imports = [
          ./../../modules/home-manager/base.nix
        ];
      };
    };
  };

  # == Secrets ==
  sops = pkgs.lib.mkMerge (map (secret: {
      secrets.${secret} = {
        neededForUsers = true;
      };
    }) [
      "lyra-password"
      "restic-remote-env"
      "restic-remote-password"
      "discord-github-releases-webhook"
      "sat-bot-discord-token"
      "sat-bot-guild-id"
      "sat-bot-n2yo-key"
    ]);

  # == Restic ==
  services.restic.backups.remote.paths = [
    "${config.services.reposilite.dataDir}/reposilite.db"
    "${config.services.reposilite.dataDir}/repositories"
    "/var/lib/minecraft-servers/minecraft-server/DiscordIntegration-Data"
    "/var/lib/minecraft-servers/minecraft-server/ops.json"
    "/var/lib/minecraft-servers/minecraft-server/whitelist.json"
    "/var/lib/minecraft-servers/minecraft-server/audioplayer_uploads"
    "/var/lib/minecraft-servers/minecraft-server/world"
  ];

  # == Nix Cache (https://nixos.wiki/wiki/Binary_Cache) ==
  services.nix-serve = {
    enable = true;
    secretKeyFile = "/var/cache-private-key.pem";
  };

  services.nginx.virtualHosts."nixcache.jamalam.tech" = {
    enableACME = true;
    forceSSL = true;
    locations."/".proxyPass = "http://${config.services.nix-serve.bindAddress}:${toString config.services.nix-serve.port}";
  };

  # == Discord GitHub Releases ==
  services.discord-github-releases = {
    enable = true;
    package = pkgs.callPackage ../../custom/discord-github-releases.nix {};
    openFirewall = true;
    settings = {
      port = 8072;

      discord_webhook_urls = [
        config.sops.secrets.discord-github-releases-webhook.path
      ];

      message = {
        username = "Release Watcher";
        avatar_url = "https://github.com/JamCoreModding.png";
        embeds = [
          {
            title = "An update has been released for $repo_name";
            url = "$release_url";
            description = "$release_body";

            fields = [
              {
                name = "Name";
                value = "$release_name";
              }
              {
                name = "Tag";
                value = "$release_tag_name";
              }
            ];

            author = {
              name = "$author_name";
              url = "$author_profile_url";
              icon_url = "$author_avatar_url";
            };
          }
        ];
      };
    };
  };

  # == Minecraft ==
  services.minecraft-servers = let
    modpack = inputs.sculk.nixFunctions.fetchSculkModpack {inherit (pkgs) stdenvNoCC sculk jre_headless;} {
      # Updated by CI
      # modpack-version-begin
      url = "https://raw.githubusercontent.com/Jamalam360/pack/dc5585d9d0876b6a3d18f62e5d803cd87975f79d";
      hash = "sha256-Nix 2.22.1
Type :? for help.
copying path '/nix/store/5w7nhyvrgsa81h0kyifmbl6j97hvlzh5-source' from 'https://cache.nixos.org'...
copying path '/nix/store/immpqad79q7wnarhlqcp0p4l9c5sc3wf-set-java-classpath-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/7gzzk927as120sja4mwqcn28jv08q6s6-gcc-13.3.0-libgcc' from 'https://cache.nixos.org'...
copying path '/nix/store/5x2mvs15awr8jc1pl03cxr58c07h52dp-gnu-config-2024-01-01' from 'https://cache.nixos.org'...
copying path '/nix/store/bihw7p4zdqwyxmnc8h67c06lnjkvdan8-xgcc-13.3.0-libgcc' from 'https://cache.nixos.org'...
copying path '/nix/store/vf553z7mi2vqk8ca6kkfd9x5gy3nnz0p-libunistring-1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/zgpc2girwbwj7iwhcrfqnkdn7y34gskd-die-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/wfc2fgb3pvjh29bsmlipzrk5si6qkmz8-set-java-classpath-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/pd8xxiyn2xi21fgg9qm7r0qghsk8715k-gcc-13.3.0-libgcc' from 'https://cache.nixos.org'...
copying path '/nix/store/mzg9fi1jl69kvf979axsbfsi1wzay53c-gnu-config-2024-01-01' from 'https://cache.nixos.org'...
copying path '/nix/store/5k2fkrnnp9w7kjvf7s0ancb5rlnml100-xgcc-13.3.0-libgcc' from 'https://cache.nixos.org'...
copying path '/nix/store/ymi1acd7jmq0xbk44cklb78gjxsswg0c-libunistring-1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/gj508ky9dssivckp7960fdglr99y80v7-mirrors-list' from 'https://cache.nixos.org'...
copying path '/nix/store/wbhgv927amhi9p91is56m4awgmgawhn3-curl-8.8.0-man' from 'https://cache.nixos.org'...
copying path '/nix/store/q9jim72sac8rdnhyxrf4z0qj9vc6446w-linux-headers-6.9' from 'https://cache.nixos.org'...
copying path '/nix/store/qm3izmaw5wn5r1abi751bwr5czm4v5xn-nghttp2-1.61.0' from 'https://cache.nixos.org'...
copying path '/nix/store/iks1pihvbilsh5sy8qvpd638k422w9i8-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/zls41s2455b6pw5d35sslf6v3gvz9349-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/pq755f1pxaas9q7666wzdzxidcvf9frg-libidn2-2.3.7' from 'https://cache.nixos.org'...
copying path '/nix/store/ilbsi0qyk6kr0l9zr8yqzwdmhw6vh2k1-libidn2-2.3.7' from 'https://cache.nixos.org'...
copying path '/nix/store/m71p7f0nymb19yn1dascklyya2i96jfw-glibc-2.39-52' from 'https://cache.nixos.org'...
copying path '/nix/store/dbwp0scbb0rk78m636sb7cvycz8xzgyh-glibc-2.39-52' from 'https://cache.nixos.org'...
copying path '/nix/store/hyn78kcvg9bggc39ldaihynfib06s9kx-attr-2.5.2' from 'https://cache.nixos.org'...
copying path '/nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26' from 'https://cache.nixos.org'...
copying path '/nix/store/ms1f510rp2z7afhq7jr81691x6456py9-bzip2-1.0.8' from 'https://cache.nixos.org'...
copying path '/nix/store/s8m5l0v1az69fnd7jfb0zr87xkpgfhza-ed-1.20.2' from 'https://cache.nixos.org'...
copying path '/nix/store/a5rvjq2ir4d1wnxwdf4a9zf6hfc6ydsx-gawk-5.2.2' from 'https://cache.nixos.org'...
copying path '/nix/store/c6r62m84hywf4i6qq1h28f13zv38yqyp-gcc-13.3.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/m9288777y854d5k0xkxgacc8rslrhb8r-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/cjnsvx7kwm56r48p75rgyyd0sy2lh5rs-lcms2-2.16' from 'https://cache.nixos.org'...
copying path '/nix/store/cdhx572ij0pvn9ayd33lk8118137j6m8-gnused-4.9' from 'https://cache.nixos.org'...
copying path '/nix/store/0dsiifpjc1cxbaa8d6b0kc6d2wijk7in-libjpeg-turbo-3.0.3' from 'https://cache.nixos.org'...
copying path '/nix/store/nm8yrdm0g59yff79qsm1xmk20xl0vg7w-pcre2-10.44' from 'https://cache.nixos.org'...
copying path '/nix/store/s5yfqhxzlcpw0ps2vb3gizicvharnd2n-xz-5.6.2' from 'https://cache.nixos.org'...
copying path '/nix/store/rc18a8k50zmrif61250sfidkqvlg41ln-zlib-1.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/wr6x94hzs5ggmpql0qx5j8q2rpfrhm7q-bzip2-1.0.8-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/z2h58nbh0xpz0h16lkmpiq8lgx464h0d-acl-2.3.2' from 'https://cache.nixos.org'...
copying path '/nix/store/0rlbqq6p9wwb7wbn5vnpck40c76czid3-xz-5.6.2-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/32yyy66vqi5ijh2nfas2nc83sw7qbgn1-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/mhk0cm9nrjs855aq1vcivra9z9g9hn44-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/0a0khkw34v25q8k6p44ma1rqa479r1za-gnutar-1.35' from 'https://cache.nixos.org'...
copying path '/nix/store/aw1kk0gvw7j4vmjxhha2fj2jfsvgrd1p-gzip-1.13' from 'https://cache.nixos.org'...
copying path '/nix/store/mdiqq9b2rvv7fajlmg3f7d6r6g78l547-gnugrep-3.11' from 'https://cache.nixos.org'...
copying path '/nix/store/pq16kam01xzd6a46gavx9z36f652pyjl-attr-2.5.2' from 'https://cache.nixos.org'...
copying path '/nix/store/wydmsg7fpk0hzzxpjwj94rys5p7crr77-bzip2-1.0.8' from 'https://cache.nixos.org'...
copying path '/nix/store/agkxax48k35wdmkhmmija2i2sxg8i7ny-bash-5.2p26' from 'https://cache.nixos.org'...
copying path '/nix/store/6mx7gxk1w5j7573p1pdb0dcmpxw2r2il-ed-1.20.2' from 'https://cache.nixos.org'...
copying path '/nix/store/bn7pnigb0f8874m6riiw6dngsmdyic1g-gcc-13.3.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/yjll8dlg38qdh9gw6bk8rsyq80jpfw3c-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/082x03cmpnsqkfp4ljrhsadz68rh3q1h-glibc-2.39-52-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/hkx0wcm23i9ihqlysri8n41kl232kawb-gawk-5.2.2' from 'https://cache.nixos.org'...
copying path '/nix/store/b8r00mlcw1zd8cx13466mcm6p9vrwn2v-gmp-6.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/18z454gyz0wpb641rw6gpqk0vi4wbxy6-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/ks6c62g0m3gqrs5i7m0cv6d6aqhdvirn-gnused-4.9' from 'https://cache.nixos.org'...
copying path '/nix/store/b5f6xzdwi2h8y7r131j0g539ry3b9yg8-nghttp2-1.61.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/sv55kjci1yyj98rdsmkf0h5942ljkk1s-keyutils-1.6.3-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/2vi70p18vgzrfsy0fxq9am9jks8kmxiq-lcms2-2.16' from 'https://cache.nixos.org'...
copying path '/nix/store/zhbvxa3v0pm7r16fj6hhshc9zdbc50fc-libjpeg-turbo-3.0.3' from 'https://cache.nixos.org'...
copying path '/nix/store/xn1zd4kcyk0vq5xfqk0ra97q35gd1v60-openssl-3.0.13' from 'https://cache.nixos.org'...
copying path '/nix/store/x9d0zrgk4pb8jwb8y441ass46yvqg8rj-acl-2.3.2' from 'https://cache.nixos.org'...
copying path '/nix/store/lqscz8qiafcc6vha719rq7ka8yv2v4rb-pcre2-10.43' from 'https://cache.nixos.org'...
copying path '/nix/store/l58j571nhm1ydqp247wk03gqf2ypz1yx-xz-5.4.6' from 'https://cache.nixos.org'...
copying path '/nix/store/cl742p1xay1zkqp2mhhxf0fy1xs1x9vr-nghttp2-1.61.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/r05c0lpbnjc8dg3rrr3ck7s07pjy86j3-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/cyc3v8qfkhn4r38a8s5d7f2c33q624mz-bzip2-1.0.8-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/bgv4pfwm49937s61bwdcd578ljkqabwg-openjdk-headless-21.0.3+9' from 'https://cache.nixos.org'...
copying path '/nix/store/knxxpiihqyi01k1dayl988wymihdp0fn-gmp-with-cxx-6.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/95ljdxg4drk1iq8jkjfq2c0z5vbwv8vm-gnutar-1.35' from 'https://cache.nixos.org'...
copying path '/nix/store/kf0ymg90210qml1f0m6bxsxx3ld4mw9i-isl-0.20' from 'https://cache.nixos.org'...
copying path '/nix/store/cyzjdgdvk169sn93i3a42k98s520jh63-mpfr-4.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/nc9lq1lra01932rfyclq3gsh82cxbmii-gzip-1.13' from 'https://cache.nixos.org'...
copying path '/nix/store/yq6n8b0mnk0qxzbs3ajsjcp8ziwqylrl-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/a44rv0x9hrjhi62dlcy5bh0xyf6rgj3v-libkrb5-1.21.2' from 'https://cache.nixos.org'...
copying path '/nix/store/4mxkh3vqhavpv4x5ib7qyiwq0k44lki5-make-shell-wrapper-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/971g0fka30djkcww2ddpx7q66dr86c1q-zlib-1.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/4vgk1rlzdqjnpjicb5qcxjcd4spi7wyw-glibc-2.39-52-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/cb62dki23j0sss0di7f2ka0mvlwkzs0j-libmpc-1.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/5dafgb8dlx02nlnxnbjk7makilq48a8b-openssl-3.0.13-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/l8n33v5ilhxakmp328pykqrawbmksgb2-gmp-with-cxx-6.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/pdqndw2kgjv8l3kd5ii0c833jqmxdanq-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/dhv5gh89him9a7ddr56cqg87zfkmjihp-coreutils-9.5' from 'https://cache.nixos.org'...
copying path '/nix/store/md9apn3290h7kv0x198ihaaa3k6icg4b-gnugrep-3.11' from 'https://cache.nixos.org'...
copying path '/nix/store/qqhrymypl970jc6npvi9a6sikhr84mdf-xz-5.4.6-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/jygpq62ygh357jih77cl55ks23888lbb-libkrb5-1.21.2-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ylmcy0liyq86s2qpbjirqf8hxl1agqcp-binutils-2.41-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/b5c03ljd9290bkp4b9356wdvncsh5ixv-openjdk-headless-21+35' from 'https://cache.nixos.org'...
copying path '/nix/store/dq03m14rqjvbz6pw42g555df4khh4bvr-zlib-1.3.1-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/lqi7xhy7cwfxl5kjcnk26k6id0fqkm1y-libssh2-1.11.0' from 'https://cache.nixos.org'...
copying path '/nix/store/qcqmiq1mb3pkk2bxbj6d6gb2fk9knk8l-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/i7qhgc0bs725qw3wdanznfkdna4z2ns2-coreutils-9.5' from 'https://cache.nixos.org'...
copying path '/nix/store/j2bgrijz55i0bkzdqfjxzb4v0px8mc9q-openssl-3.0.13-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/zc0nsv23pakbafngjy32kvhfzb16as43-gcc-13.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/8ynk6xvczjnjv81bfghkjwrap0hn6qah-diffutils-3.10' from 'https://cache.nixos.org'...
copying path '/nix/store/j71whmq49hfcvhpn4wqzrqcnbq5mafic-findutils-4.10.0' from 'https://cache.nixos.org'...
copying path '/nix/store/gisf1pybvzqh54p6bqi0j5jphf7yh4wy-curl-8.8.0' from 'https://cache.nixos.org'...
copying path '/nix/store/j4gkc44c1pwl5ccgxm83s4r746bsdcw9-diffutils-3.10' from 'https://cache.nixos.org'...
copying path '/nix/store/z34q08316lfq1rkx2birn1b0wyaccndh-libssh2-1.11.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/rr1yixvn0z63mgq9s04ig9j9qlz23s2g-findutils-4.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/wwfrj9kvfi14xclc38qfwm71ah6aawdh-binutils-2.41' from 'https://cache.nixos.org'...
copying path '/nix/store/z004gzhs1p6z755lrq4qzvzrp9b0r8xb-stdenv-linux' from 'https://cache.nixos.org'...
copying path '/nix/store/faxwwqxm0gx52avxvig2nw6g9kj8ghq5-curl-8.8.0-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/5gl8z4mxbfx4x4r5lamq9ccv4n7l6f1i-stdenv-linux' from 'https://cache.nixos.org'...
copying path '/nix/store/9zifdbbqh2rwd8g92zjhax7s337i9lnk-curl-8.8.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/l46fjkzva0bhvy9p2r7p4vi68kr7a1db-binutils-wrapper-2.41' from 'https://cache.nixos.org'...
building '/nix/store/13cfac4kprmjs9qvr8b832zy6kxyc2y6-sculk-0.1.0+beta.14.jar.drv'...
copying path '/nix/store/mpm3i0sbqc9svfch6a17179fs64dz2kv-gcc-wrapper-13.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/d3dzfy4amjl826fb8j00qp1d9887h7hm-stdenv-linux' from 'https://cache.nixos.org'...
building '/nix/store/bai48rmcf75347qxx3sigpwiwp0jmvbp-sculk-0.1.0+beta.14.drv'...
building '/nix/store/9lrlpm2m7c32w7hp6kvb4yz41p090shf-sculk-modpack-.drv'...
error: builder for '/nix/store/9lrlpm2m7c32w7hp6kvb4yz41p090shf-sculk-modpack-.drv' failed with exit code 1;
       last 25 log lines:
       >         at io.ktor.utils.io.charsets.CharsetJVMKt.decode(CharsetJVM.kt:241)
       >    at io.ktor.utils.io.charsets.EncodingKt.decode(Encoding.kt:103)
       >        at io.ktor.utils.io.charsets.EncodingKt.decode$default(Encoding.kt:101)
       >        at io.ktor.client.statement.HttpResponseKt.bodyAsText(HttpResponse.kt:89)
       >      at io.ktor.client.statement.HttpResponseKt.bodyAsText$default(HttpResponse.kt:84)
       >      at tech.jamalam.commands.Install.readFile(Install.kt:167)
       >      at tech.jamalam.commands.Install.access$readFile(Install.kt:30)
       >        at tech.jamalam.commands.Install$readFile$1.invokeSuspend(Install.kt)
       >  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       >      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       >        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
       >      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
       >   at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
       >       at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
       >   at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
       >       at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
       >   at tech.jamalam.commands.Install.run(Install.kt:38)
       >    at com.github.ajalt.clikt.parsers.Parser.finalizeAndRun(Parser.kt:348)
       >         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:218)
       >  at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:245)
       >  at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:42)
       >   at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:457)
       >         at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:461)
       >         at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:460)
       >         at tech.jamalam.MainKt.main(Main.kt:68)
       For full logs, run 'nix log /nix/store/9lrlpm2m7c32w7hp6kvb4yz41p090shf-sculk-modpack-.drv'.";
      # modpack-version-end
    };

    # inspo: https://github.com/Infinidoge/nix-minecraft/pull/43
    collectFiles = let
      inherit (pkgs) lib;
      mapListToAttrs = fn: fv: list:
        lib.listToAttrs (map (x: lib.nameValuePair (fn x) (fv x)) list);
    in
      path: prefix:
        mapListToAttrs
        (x: builtins.unsafeDiscardStringContext (lib.removePrefix "${path}/" x))
        (lib.id) (lib.filesystem.listFilesRecursive "${path}/${prefix}");
  in {
    enable = true;
    eula = true;
    openFirewall = true;
    dataDir = "/var/lib/minecraft-servers";

    servers.minecraft-server = {
      enable = true;
      package = pkgs.minecraftServers.fabric-1_20_1;
      autoStart = true;
      restart = "always";
      symlinks = {
        "mods" = "${modpack}/mods";
      };
      files =
        collectFiles "${modpack}" "config"
        // {
          "config/Discord-Integration.toml" = "/var/lib/Discord-Integration.toml";
        };
      serverProperties = {
        server-port = 25565;
        white-list = true;
        level-seed = 5716240849493836707;
        view-distance = 20;
      };
      jvmOpts = "-Xmx10G -Xms10G";
    };
  };
  networking.firewall.allowedUDPPorts = [24454]; # Simple Voice Chat mod

  # == Reposilite ==
  services.reposilite = {
    enable = true;
    package = pkgs.callPackage ../../custom/reposilite.nix {};
    settings = {
      port = 8084;
    };
  };

  # == Sat Bot ==
  services.sat-bot = {
    enable = true;
    package = pkgs.callPackage ./../../custom/sat-bot.nix {};
    settings = {
      discordToken = config.sops.secrets.sat-bot-discord-token.path;
      guildId = config.sops.secrets.sat-bot-guild-id.path;
      n2yoKey = config.sops.secrets.sat-bot-n2yo-key.path;
    };
  };
}
