name: Check

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - run: nix fmt -- --check .

  statix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - run: nix run nixpkgs#statix -- check
