name: Update flake.lock

on:
  schedule:
    - cron: 0 6 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v26
      - run: nix flake update
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "deps: update flake.lock"
          commit_user_name: GitHub Actions
          commit_options: --no-verify --signoff
          commit_author: GitHub Actions <actions@github.com>
          branch: main
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true
