name: Update Fetchers (Static Sites & Modpack)

on:
  schedule:
    - cron: 0 6 * * *
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
  
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update CDN
        run: nix develop -c ".github/workflows/update.sh github modules/lyra-services/cdn.nix"
      - name: Update It's Clearing Up
        run: nix develop -c ".github/workflows/update.sh github modules/lyra-services/its-clearing-up.nix"
      - name: Update Minecraft (Vanilla)
        run: nix develop -c ".github/workflows/update.sh modpack modules/lyra-services/minecraft/vanilla.nix"
      - name: Update Minecraft (Modded)
        run: nix develop -c ".github/workflows/update.sh modpack modules/lyra-services/minecraft/modded.nix"
      - name: Update Teach Man Fish
        run: nix develop -c ".github/workflows/update.sh github modules/lyra-services/teach-man-fish.nix"
      - name: Update Discord GitHub Releases
        run: nix develop -c ".github/workflows/update.sh github pkgs/discord-github-releases.nix"
      - name: Update Pinguino Quotes
        run: nix develop -c ".github/workflows/update.sh github pkgs/pinguino-quotes.nix"
      - name: Update Sat Bot
        run: nix develop -c ".github/workflows/update.sh github pkgs/sat-bot.nix"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update fetchers"
          commit_user_name: GitHub Actions
          commit_options: --no-verify --signoff
          commit_author: GitHub Actions <actions@github.com>
          branch: main
          skip_dirty_check: false
          skip_fetch: true
